path: /blog/general
tag: blog-general
title: General
color: purple
tabs:
  - href: /blog
    title: Latest
  - href: /blog/featured
    title: Featured
  - href: /blog/general
    title: General
  - href: /blog/api-design
    title: API Design
  - href: /blog/api-documentation
    title: API Documentation
  - href: /blog/api-testing
    title: API Testing
  - href: /blog/changelog
    title: Changelog
actionBar:
  enabled: true
meta:
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: General | Stoplight API Corner
  twitter:
    title: General | Stoplight API Corner
    username: '@stoplightio'
pagination:
  enabled: true
